language: node_js
node_js:
- 10.15.0
script:
- npm run lint
- npm run rollup
- npm run babel
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file: dist/mini-humidifier-bundle.js
  on:
    repo: artem-sedykh/mini-humidifier